language: c

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/askovpen/huskylib ~/askovpen/huskylib
script:
  - pwd
  - cd  ~/askovpen/huskylib
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make install
  - cd  ~/askovpen/smapi
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cpack
